# Generated by Django 4.1 on 2025-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
