# Generated by Django 4.1 on 2025-10-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_failure_description_alter_order_failure_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
