# Generated by Django 4.1 on 2025-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_razorpay_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='profile-images/default.png', upload_to='profile-images/'),
        ),
    ]
