# Generated by Django 4.1 on 2025-10-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myorder',
        ),
    ]
