# Generated by Django 4.1 on 2025-11-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
