# Generated by Django 4.1 on 2025-11-03 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9e8ceb5e-5745-4677-8f7e-fdab16b8a6a6'), editable=False, unique=True),
        ),
    ]
