# Generated by Django 4.1 on 2025-11-05 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
