# Generated by Django 4.1 on 2025-11-05 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_myorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
