# Generated by Django 4.1 on 2025-11-05 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_myorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
